#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
	/Applications/MacPorts/Emacs.app/Contents/MacOS/bin/emacsclient -nw $*
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
	emacsclient -nw "$@"
fi
