#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
	/Applications/MacPorts/Emacs.app/Contents/MacOS/bin/emacsclient -e "(kill-emacs)"
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
	emacsclient -e "(kill-emacs)"
fi
