#!/bin/bash

# Script to join vtk files
# modified from joinppm.sh by Sasha Philippov, need program joinvtk

# Usage is, e.g.,
# mine_joinvtk -i FP -o comb/FPc -f 1:4 -p 16 -s d.vtk

# That will take the d.vtk files from the id*/ sub-directories of the current
# directory and put the output (changing the filename from FP*.ppm to FPc*.ppm
# so you don't confuse the two) in the sub-directory comb (which it will
# create, if necessary). -x and -y specify the mpi decomposition of the
#computational domain. See also below.

scrdir=$(dirname $0)
script=$(basename $0)

# set defaults
dir=$(pwd)
ext="vtk"
existid0=1
usesub=1
fs=1

# ***************************************************************************

usage ()
{
  echo "This script joins vtk files."
  echo ""
  echo "Options:"
  echo "  -i inbase"
  echo "          Base of input files (e.g. Turb for Turb-id1.0000.vtk)"
  echo "  -o outbase"
  echo "          Base of output files (e.g. combined for combined.0000.vtk)"
  echo "  [-s extension]"
  echo "          File extension (e.g. d.vtk for Turb.0000.d.vtk) [vtk]"
  echo "  -f {f|f0:fn|f0:fn:fi}"
  echo "          Join specific file number (f) OR file range (f0 thru fn) OR"
  echo "          sequence of files (f0 thru fn at intervals fi)"
  echo "  -p {nproc|p0:pn}"
  echo "          Number of processors (nproc) OR processor range (p0 thru pn)"
  echo "  [-d dir]"
  echo "          Input directory [.]"
  echo "  [-z]"
  echo "          Root process does not write to id0 sub-directory"
}

# ***************************************************************************

checkparset ()
{
  if [ "X$2" == "X" ]; then
    echo "Error:  $1"
    usage
    exit 1
  fi
}

# ***************************************************************************

checkopts ()
{ # validate parameters
  checkparset "Input base name not set! (use -i)" ${ibase}
  checkparset "Output base name not set! (use -o)" ${obase}

  checkparset "Processor range not set! (use -p)" ${p0}
  checkparset "Processor range not set! (use -p)" ${pn}

  if [ ${p0} -lt 0 ]; then
    echo "The starting processor number cannot be negative."
    usage
    exit 1
  fi
  if [ ${pn} -lt 0 ]; then
    echo "The number of processors must be positive."
    usage
    exit 1
  fi
  if [ ${pn} -lt ${p0} ]; then
    echo "The ending processor number cannot be smaller than the starting."
    usage
    exit 1
  fi

  checkparset "File range not set! (use -f)" ${f0}
  checkparset "File range not set! (use -f)" ${fn}
  checkparset "File range not set! (use -f)" ${fs}

  if [ ${f0} -lt 0 ]; then
    echo "The starting file number cannot be negative."
    usage
    exit 1
  fi
  if [ ${fn} -lt ${f0} ]; then
    echo "The ending file number cannot be smaller than the starting."
    usage
    exit 1
  fi
  if [ ${fs} -lt 0 ]; then
    echo "The file interval cannot be negative."
    usage
    exit 1
  fi
}

# ***************************************************************************

padstring ()
{
  # pad the file number with zeros
  if [ $FNO -lt 10 ]; then
    FNOSTR="000${FNO}"
  elif [ $FNO -lt 100 ]; then
    FNOSTR="00${FNO}"
  elif [ $FNO -lt 1000 ]; then
    FNOSTR="0${FNO}"
  else
    FNOSTR="${FNO}"
  fi
}

sourcelist ()
{
  # construct list of source files
  xp0=$1
  xpn=$2
  xibase=$3
  xcap=$4
  xusesub=$5
  xext=$6

  xp1=${xp0}
  src=""
  sub=""
  if [ ${existid0} -eq 0 ]; then
    if [ ${xp0} -eq 0 ]; then
      src="${xibase}.${FNOSTR}.${xext}"
      xp1=1
    fi
  fi
  for ((a=${xp1} ; a<=${xpn} ; a++)) ; do
    if [ ${xusesub} -ne 0 ]; then
      sub="id${a}/"
    fi
    if [ ${a} -ne 0 ]; then
      src="${src} ${sub}${xibase}${xcap}${a}.${FNOSTR}.${xext}"
    else
      src="${src} ${sub}${xibase}.${FNOSTR}.${xext}"
    fi
  done
}

# ***************************************************************************

while getopts "nwzd:f:b:i:o:p:s:x:y" opt ; do
  case $opt in
    "z" )
#      echo "root process doesn't write to id0"
      existid0=0
      ;;
    "d" )
      dir=${OPTARG}
#      echo "source file full path ${dir}"
      ;;
    "f" )
      cnt=$(echo "${OPTARG}" | awk "{ cnt = split(\$0,a,\":\"); print cnt }")
      if [ ${cnt} -eq 1 ]; then
        f0=${OPTARG}
        fn=${f0}
#        echo "file ${f0}"
      else
        if [ ${cnt} -eq 2 ]; then
          f0=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[1] }")
          fn=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[2] }")
#          echo "files ${f0} through ${fn}"
        else
          f0=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[1] }")
          fn=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[2] }")
          fs=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[3] }")
#          echo "files ${f0} through ${fn} with interval ${fs}"
	fi
      fi
      ;;
    "b" )
      ibase=${OPTARG}
#      echo "source file base ${ibase}"
      ;;
    "i" )
      ibase=${OPTARG}
#      echo "source file base ${ibase}"
      ;;
    "o" )
      obase=${OPTARG}
#      echo "output file base ${obase}"
      ;;
    "p" )
      cnt=$(echo "${OPTARG}" | awk "{ cnt = split(\$0,a,\":\"); print cnt }")
      if [ ${cnt} -eq 1 ]; then
        p0=0
        pn=$[${OPTARG}-1]
#        echo "procs 0 through ${pn}"
      else
        p0=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[1] }")
        pn=$(echo "${OPTARG}" | awk "{ split(\$0,a,\":\"); print a[2] }")
#        echo "procs ${p0} through ${pn}"
      fi
      ;;
    "s" )
      # e.g. vtk or d.vtk
      ext=${OPTARG}
#      echo "source file extension ${ext}"
      ;;

    * )
      badsyn=1
#      echo "invalid option"
  esac
done
shift $(($OPTIND - 1))

# validate parameters
checkopts

# create the output directory if needed
osub=$(dirname ${obase})
if [ "X${osub}" != "X" ]; then
  mkdir ${osub}/ 2>/dev/null
fi

# for FNO in `seq ${f0} ${fn}`; do
for ((FNO=${f0} ; FNO <= ${fn} ; FNO += ${fs})) ; do
  # pad the file number with zeros
  padstring

  # construct list of source files and join them
  # write to single vtk file
  sourcelist ${p0} ${pn} ${ibase} "-id" ${usesub} ${ext}
  #echo ${src}
  outfile="${obase}.${FNOSTR}.${ext}"
  #echo ${outfile}
  echo "join to ${outfile}"
  # join the files
  join_vtk -o ${outfile} ${src}

done
