#!/bin/sh
default_postfix="jpg"
default_framerate=30
postfix=${1:-$default_postfix}
frate=${2:-$default_framerate}

ffmpeg -r $frate -pattern_type glob -i "*.${postfix}" -c:v libx264 -pix_fmt yuv420p output.mp4
#end
