#!/bin/bash
#ffmpeg -start_number 100 -f image2 -r 24 -pattern_type glob -i "*.jpg" -vcodec mjpeg -qscale 8 -s 640x480 -b 1M output.mov
convert *.ppm temp.%05d.jpg
ffmpeg -r 30 -pattern_type glob -i "*.jpg" -c:v libx264 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv420p output.mp4
rm *.jpg
#end
