#!/bin/bash
if [[ -n `ls *hst` ]]
then
	rm *hst
fi

if [[ -n `ls *rst` ]]
then
	rm *rst
fi

if [[ -n `ls *txt` ]]
then
	rm *.txt
fi

if [[ -n `ls *vtk` ]]
then
	rm *.vtk
fi

if [[ -n `ls *lis` ]]
then
	rm *.lis
fi

if [[ -n `ls *err` ]]
then
	rm *err
fi

if [[ -n `ls *out` ]]
then
	rm *out
fi

if [[ -n `ls core` ]]
then
	rm core
fi

if [ -d id0 ]
then
	rm -rf id*
fi

if [ -d comb ]
then
	rm -rf comb
fi

if [ -d lev1 ]
then
	rm -rf lev*
fi
