#!/usr/bin/env bash
default_crf="23"
default_preset="medium"
default_rate="60"
default_out="${1%.*}-hevc.mp4"
crf=${2:-$default_crf}
preset=${3:-$default_preset}
frate=${4:-$default_rate}
out=${5:-$default_out}

ffmpeg -hide_banner \
-i $1 \
-r $frate \
-map_metadata 0 \
-map_chapters 0 \
-c:v libx265 -preset $preset -crf $crf \
-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv420p -tag:v hvc1  \
-c:a copy \
-c:s copy \
-color_primaries 1 -color_trc 1 -colorspace 1 \
$out

# -tag:v hvc1 -tag:a ac-3 \ # add hvc1 to make QuickTime Player to recognize it, sometimes ac-3 is needed
# -r $frate is added because somehow ffmpeg change 64.40 video to 120fps, weird

# For more options, see 
# https://unix.stackexchange.com/questions/230800/re-encoding-video-library-in-x265-hevc-with-no-quality-loss

#end
